### ISSUE TITLE
Off-by-1 in domain coordinates

### ISSUE THREAD

**Issue by zdk123** [medema-group/BiG-SCAPE#1]
Python uses 0-indexing with an exclusive end coordinate. The hmmer3 domain table (from/to) uses 1-indexing with an includive end coordinate.

However it *looks* like, when subsetting sequences for the domain fasta files, the start coordinates [are not adjusted](https://github.com/medema-group/BiG-SCAPE/blob/master/functions.py#L448-L4497).

Therefore, it seems that the amino acid sequences associated with domains are missing the first residue in the fasta output.

[This line](https://github.com/medema-group/BiG-SCAPE/blob/master/functions.py#L237
) should be
```diff
-            seq[int(row[3]):int(row[4])])) #only use the range of the pfam domain within the sequence
+            seq[(int(row[3])-1):int(row[4])])) #only use the range of the pfam domain within the sequence
```

**Comment by jorgecnavarrom** [comment]
Good catch! Thanks Zachary
Fixed in [7f347c5](https://github.com/medema-group/BiG-SCAPE/commit/7f347c541148160595e07510d19968c63456d012)
