### ISSUE TITLE
distance calculation

### ISSUE THREAD

**Issue by INFINITY1993** [medema-group/BiG-SCAPE#11]
Hi，
Thanks for the development of such an amazing tool.
I am curious about the distance calculation of BGC pair. Where could I find the calculation formula? 
Thanks.

**Comment by jorgecnavarrom** [comment]
Hi
We basically combine three indices to make up for the distance calculation. You can read more details about this in the Online Methods of the publication (free version: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6917865/#S9title) and in the Supplementary Note 1 section of the second supplementary file

**Comment by INFINITY1993** [comment]
Thanks for your reply. I surely read the Supplementary Note 1 and the methods section of the article, and I know that three indices were used for distance calculation, but how the three indices were combined? It seems not shown in the paper. Does it like the following formula shows?
Jw*Jaccard index + DSSw*DSS index + AIw*Adjacency index

Another question is that how I should choose the threshold cutoff to build the BGCs network? The default cutoff is 0.3 in your paper, while 0.65 was used in another research project ([Global analysis of biosynthetic gene clusters
reveals conserved and unique natural products in entomopathogenic nematode-symbiotic bacteria](https://www.nature.com/articles/s41557-022-00923-2))

Thanks again!

**Comment by INFINITY1993** [comment]
That's helpful. Thanks!

**Comment by jorgecnavarrom** [comment]
Great to hear!
