### ISSUE TITLE
How to install the latest Bigscape?

### ISSUE THREAD

**Issue by Airynan** [medema-group/BiG-SCAPE#111]
Hi there,
I noticed that the latest version of bigscape was released, the updates for prodigosine  is important to me. However, The original version of biscape was installed by me based on the command lines you gived on the tutorial with docker. but I don't know how to install the latest version with a compressed packages.
Is there possible to install the latest version by the same command on the tutorial ?

Thanks.

**Comment by Airynan** [comment]
Sorry, I have got the answers from the Wiki page and installed the latest version succesffully by conda. But I cannot perform bigscape in other files excepting the installing file, even after the  path addition of bin of bigscape to the system. Can you give me some suggestions ?

**Comment by adraismawur** [comment]
Hello!

The 1.x.x version of BiG-SCAPE is not installable as an application that can be run from any directory, unfortunately.

Could you describe your data structure/situation that you are using? Perhaps we can give some suggestions based on that.

**Comment by adraismawur** [comment]
Hello, this issue is stale and I will close it here, but in case you still have issues please feel free to re-open this issue.
