### ISSUE TITLE
Update of the BiG-SCAPE bioconda recipe

### ISSUE THREAD

**Issue by SantaMcCloud** [medema-group/BiG-SCAPE#115]
Hello,

currently, I am working on creating a wrapper for BiG-SCAPE, so this tool can be added to Galaxy (https://usegalaxy.org), a bioinformatic tool collection. Before I create a PR, I wanted to ask if these changes are fine for you (https://github.com/bioconda/bioconda-recipes/compare/master...SantaMcCloud:bioconda-recipes:conda_recipes_update?expand=1). 

I only did change the version to the newest version. I did try to work with the current recipe, but after installing it I got a bug where the fasta dir could not be used in the functions. After trying out the current version, this bug doesn't appear and the tool function fine now!

**Comment by adraismawur** [comment]
Hi!

Thank you! Feel free to update the Bioconda version, but I am not certain how well that version works as an installable package (see https://github.com/medema-group/BiG-SCAPE/issues/103#issuecomment-1880621938)

We will make an effort to keep an updated bioconda version starting from version 2

**Comment by adraismawur** [comment]
Looks like this is all set now with #122
