### ISSUE TITLE
bump version number?

### ISSUE THREAD

**Issue by hyphaltip** [medema-group/BiG-SCAPE#116]
https://github.com/medema-group/BiG-SCAPE/blame/b72495759af402e3e07b3954269ca9bdf1ac52f8/setup.py#L20

should this be 1.1.7 per the version released?

**Comment by adraismawur** [comment]
Hi!

Sorry for the oversight, it certainly should!
However we will try to make as few changes as possible to version 1 of BiG-SCAPE as we are approaching our version 2 release. 

Is this causing problems for your installation? If so we can bump the version number.

**Comment by hyphaltip** [comment]
i think there was a problem replacing old version maybe, can't remember, but spotted this and changed it locally anyways.

**Comment by adraismawur** [comment]
This is now done in #123
