### ISSUE TITLE
BGC_fasta_folder is not defined

### ISSUE THREAD

**Issue by haseebmanzur** [medema-group/BiG-SCAPE#117]
I am repeatedly getting this error, the fasta files are not generated in the output folder hence this error arises. But I haven't been able to figure out why the aligned files are not generated. I did everything I could. Please guide. FYI I'm using Bigscape 1.1.5
![bigscape_issue](https://github.com/medema-group/BiG-SCAPE/assets/140144044/355ef8e5-81c3-4801-a7f8-a33a55222f48)

**Comment by adraismawur** [comment]
Hello,

How did you install BiG-SCAPE? It looks like it is installed as a package.

Can you try downloading big-scape 1.1.5 from this link, extracting it to a folder and running it from there?
https://github.com/medema-group/BiG-SCAPE/archive/refs/tags/v1.1.5.zip

**Comment by haseebmanzur** [comment]
I installed it through bioconda.
Command:
mamba install -c bioconda bigscape

**Comment by haseebmanzur** [comment]
Issue resolved through extracting bigscape from the link you provided. Bundle o thanks.
