### ISSUE TITLE
Stopped at Hmmalign  step

### ISSUE THREAD

**Issue by planctoqueen** [medema-group/BiG-SCAPE#119]
Hi!

I'm trying to run a new database (22k regions), and everytime I do it the kob dies at the hmmalign step, but it gives no error (as you can see in the image)

I tried to run with other databases and it all works ok. And I tried to run this databasein two different computadors and the hmmalign gets killed in both.

Do you have any idea of what may be the issue? It can be do the size of the database?

Thanks!

![image](https://github.com/medema-group/BiG-SCAPE/assets/60857163/a49abe04-8b56-4df6-ab68-178caa45915c)

**Comment by adraismawur** [comment]
Hello!

I have two questions to diagnose the issues further:
- Could you tell us how long it takes until the job dies?
- How much memory is available on the machine?

It is difficult to say what the issue could be. My intuition is that the hmmalign program crashes after a while, but I am not sure what the reason for that could be.

**Comment by jorgecnavarrom** [comment]
Since it stops at the hmm align step, I wonder if it could be that there are ambiguous residues in any of your dataset's sequences (e.g. 'X' characters)?

**Comment by planctoqueen** [comment]
Thank you !

- Yes, I am incline to a "time out" situation, since it will crash after many hours (maybe 10 hours or more. I am now running it again, with a timmer to have a clear answer on this). However I have no ideia how I can solve it. 
- 
- I have currently 8 GB RAM allocated for this.
- 
- Also yes,  I probably have some "X" characters but in previous(smaller) runs, it always displays some message saying that, but it continues anyways, so I'm not quite sure if this is the issue.

**Comment by adraismawur** [comment]
This is strange. I don't think the ram should be the issue, and the unknown characters case should indeed be handled.

Is it possible that you add a print statement to the code to see which file it crashes on?
