### ISSUE TITLE
cannot view index.html and tutorial files won't unzip

### ISSUE THREAD

**Issue by jfoldi81** [medema-group/BiG-SCAPE#142]
Hello,
I was trying to run BiG-SCAPE for some antiSMASH runs but the index.html file is blank. This is my run output. 

   - - Processing input files - -
 Including files with one or more of the following strings in their filename: 'cluster', 'region'
 Skipping files with one or more of the following strings in their filename: 'final'

Importing GenBank files
  Warning: unknown product 'NI-siderophore'

 Starting with 7 files
 Files that had its sequence extracted: 7

Creating output directories

Trying threading on 16 cores

Predicting domains using hmmscan
 Predicting domains for 7 fasta files
 Finished generating domtable files.

Parsing hmmscan domtable files
 Processing 7 domtable files
 New domain sequences to be added; cleaning domains folder
 Finished generating pfs and pfd files.

Processing domains sequence files
 Adding sequences to corresponding domains file
 Reading the ordered list of domains from the pfs files
 Creating arrower-like figures for each BGC
  Parsing hmm file for domain information
    Done
  Found file with domains colors
  Reading BGC information and writing SVG
/home/jonF/miniconda3/envs/prokka/lib/python3.12/site-packages/Bio/SeqFeature.py:230: BiopythonDeprecationWarning: Please use .location.strand rather than .strand
  warnings.warn(
 Finished creating figures

   - - Calculating distance matrix - -
Performing multiple alignment of domain sequences

 Using hmmalign
launch_hmmalign took 1.029 seconds
 Trying to read domain alignments (*.algn files)

Generating distance network files with ALL available input files
   Writing the complete Annotations file for the complete set

 Working for each BGC class
  Sorting the input BGCs

  Warning: unknown product 'NI-siderophore'

  RiPPs (2 BGCs)
   Writing annotation files
   Calculating all pairwise distances
generate_network took 0.052 seconds
   Writing output files
  Calling Gene Cluster Families
  Cutoff: 0.3
/home/jonF/miniconda3/envs/prokka/lib/python3.12/site-packages/sklearn/cluster/_affinity_propagation.py:52: UserWarning: All samples have mutually equal similarities. Returning arbitrary cluster center(s).
  warnings.warn(

  Others (3 BGCs)
   Writing annotation files
   Calculating all pairwise distances
generate_network took 0.054 seconds
   Writing output files
  Calling Gene Cluster Families
  Cutoff: 0.3
/home/jonF/miniconda3/envs/prokka/lib/python3.12/site-packages/sklearn/cluster/_affinity_propagation.py:52: UserWarning: All samples have mutually equal similarities. Returning arbitrary cluster center(s).
  warnings.warn(

  NRPS (3 BGCs)
   Writing annotation files
   Calculating all pairwise distances
generate_network took 0.052 seconds
   Writing output files
  Calling Gene Cluster Families
  Cutoff: 0.3
/home/jonF/miniconda3/envs/prokka/lib/python3.12/site-packages/sklearn/cluster/_affinity_propagation.py:52: UserWarning: All samples have mutually equal similarities. Returning arbitrary cluster center(s).
  warnings.warn(

  Terpene (1 BGCs)
   Writing annotation files
   Calculating all pairwise distances
generate_network took 0.042 seconds

  PKSother (1 BGCs)
   Writing annotation files
   Calculating all pairwise distances
generate_network took 0.045 seconds

  Saccharides (1 BGCs)
   Writing annotation files
   Calculating all pairwise distances
generate_network took 0.046 seconds

	Main function took 26.904 s

<img width="1485" alt="Screenshot 2024-04-05 at 11 07 07 AM" src="https://github.com/medema-group/BiG-SCAPE/assets/36321975/56487727-ca81-4eb1-ad33-35402a6dad5f">

I wasn't sure if this was an issue with my files so I tried following the tutorial but cannot unzip the genome files, as I get this error. 
`All samples have mutually equal similarities. Returning arbitrary cluster center(s).`

Please let me know if any other information would be useful for troubleshooting either of these issues!

**Comment by CatarinaCarolina** [comment]
Hi!

Is there any chance you might have moved the index.html file outside of the output folder? That would explain the issue, the index.html must be opened from its folder as outputted by BiG-SCAPE.

Re unzipping tutorial files, could you provide some more detail? the error message you describe is produced by the clustering algorithm package (performing affinity propagation), and does not seem related to a (un)zip error?

Cheers,
Catarina

**Comment by jfoldi81** [comment]
@CatarinaCarolina 
Thank you so much for the help! I'd been downloading the index.html from a remote server so that I could open it with a browser locally which did not work but just transferred the entire output directory to my local computer and am now able to view it!

Apologies I mistyped the error for unzipping.

```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by CatarinaCarolina** [comment]
what is the command you are using for unzipping?

`tar xzf gbks.tar.gz ` should do the trick!

**Comment by CatarinaCarolina** [comment]
You can try wget https://zenodo.org/records/1340706/files/gbks.tar.gz
or directly download from the zenodo page https://zenodo.org/records/1340706

both options seem to work fine on my end.

**Comment by jfoldi81** [comment]
@CatarinaCarolina 
That new zenodo link worked, and it seems my issue had been that the link in the wget command [here](https://github.com/nselem/bigscape-corason/blob/master/scripts/data_bigscape_corason.sh) was for Version 1 for gbks.tar.gz and genomes.tar.gz which did not unzip even when I tried downloading directly from the zenodo page. 

Thanks for all the help!
