### ISSUE TITLE
Random BGC families not showing in mixed class

### ISSUE THREAD

**Issue by EdderDaniel** [medema-group/BiG-SCAPE#148]
Hi! I do not know if this is a bug, but whenever i use the mixed option--which as far as i understand should group all BGC families together--random BGC families that show up in other classes (NRPS, terpenes, etc...) do not appear in the mixed categorie. Is there a reason for this or am i not getting something?

I am using BiG-SCAPE 1.1.8 (2022-11-14)

**Comment by jorgecnavarrom** [comment]
Hi
The mix mode would calculate the similarity between every pair of regions in the input dataset. It uses a more general set of weights, so the families resulting from mix mode could be different than the ones generated in a particular biosynthetic class. 

> random BGC families that show up in other classes (NRPS, terpenes, etc...) do not appear in the mixed categorie

Do you mean the GCF number does not appear, or that GCF that was observed in the specific class is now broken up in the Mix class?

**Comment by EdderDaniel** [comment]
Thanks for the clarification! So, if i understand correctly, the GCFs from mixed do not map one to one to the GCFs from the other categories, right? My specific problem is that when i searched for a specific family from another categorie (for example, FAM_0234 from NRPS) in the mixed category that specific family (the number, as you mentioned) did not exist but technically, the GCF might be there under another name, correct?

**Comment by jorgecnavarrom** [comment]
Yes, that's correct! The FAM number is the internal number of the central node (the 'exemplar', as called in the affinity propagation algorithm). This corresponds to the line number (shifted a bit by 2 I think) in the Network Annotations file.
This exemplar may vary between biosynthetic classes (if it belongs to more than one) or cutoff used.
