### ISSUE TITLE
index.html won't finish loading data

### ISSUE THREAD

**Issue by Matt-BF** [medema-group/BiG-SCAPE#151]
Hi! Thanks for this great software, and sorry if this has already been answered, but I can't find any similar issues open or closed.

I ran BiG-SCAPE against my antiSMASH outputs (around 6k BGCs), which apparently ran successfully. However, when opening the index.html in my browser, the home page shows loading data and it never finishes. I am able to open the network pages for each of the classes, so the problem is only on the overview page.

Thanks in advance for your help!

**Comment by CatarinaCarolina** [comment]
Hi Mateus!

Could you give us a bit more detail on how are you opening the individual network pages for each of the classes?

And any changes to the output folder structure of BiG-SCAPE that might have happened? (If there are changes to this folder structure then that might be causing the issue)

Cheers,
Catarina

**Comment by Matt-BF** [comment]
Sure, thanks for the quick reply! I am opening by clicking the network tabs on the home page. The overview page is the only one that will not load
![image](https://github.com/medema-group/BiG-SCAPE/assets/35854519/6c2be13d-d6fc-47e0-8ce6-6d247403a695)

I don't think there are any problems with the output structure, as there were no errors, apart form some unknown products and python deprecation warnings on the run. Also, I had already ran BiG-SCAPE for the same files, with the exception of a new set of genomes which I added to my antiSMASH pipeline. Maybe the final output got "too heavy" to parse?

**Comment by CatarinaCarolina** [comment]
Hi Mateus,

Sorry for the late reply!

Ok thats quite odd, it could be indeed that its getting to heavy (we're hopefully addressing this in v2)

If your data isn't sensitive/private you can also send us the html_content/networks/{run_folder}/run_data.js and we have a look if we can see anything more that might be going on!

cheers!
Catarina

**Comment by Matt-BF** [comment]
Hi Catarina!

The file is indeed quite large (600MB), and after compressing it still was to big to add here or through email, so I shared it with you through google drive

Thanks again for your help!

**Comment by CatarinaCarolina** [comment]
Hi Mateus!

Thanks for sharing! we looked a bit into this and its indeed a size limitation, we could replicate this issue in chrome and edge, but firefox and safari still seem to load it, so for now you could try one of those.

For v1 we wont fix this but we'll hopefully be able to address this better in v2 :)

Cheers,
Catarina

**Comment by Matt-BF** [comment]
Ah, that's great, I had just tried in Brave and Arc browser, which are both chromium, but never thought about trying Firefox or Safari. It loaded in Safari, so that's good enough for me! Thanks for your help!
