### ISSUE TITLE
Network_Annotations_Full.tsv result 

### ISSUE THREAD

**Issue by liangly1** [medema-group/BiG-SCAPE#156]
Hello, I used the results obtained from the antismash software as input to a specified folder and got the Network_Annotations_Full.tsv file. Why does the BGC column in the table show results like BGC0000001, BGC0000002? Shouldn't it output the names of the gbk files I input, such as ABTEK_DN1_1.region001?I have another question. Hello, I was able to open the webpage after switching to a different browser, but I have another question. Why does it only show one specified genome? I have 45 folders under the antismash_res directory, each representing a different genome. The input directory is the result folder obtained from Antismash.

**Comment by jorgecnavarrom** [comment]
> Why does the BGC column in the table show results like BGC0000001, BGC0000002? 

Those are the MIBiG reference BGCs. Did you use option `--mibig`?

>Why does it only show one specified genome? I have 45 folders 

The number of genomes is not based on the number of folders in your `input_folder` but rather on the information on each gbk header (so if you have several repeated names like "contig001.region001", it will only be counted once)
