### ISSUE TITLE
ConvergenceWarning: Affinity propagation did not converge, this model will not have any cluster centers.

### ISSUE THREAD

**Issue by tiagolbiotech** [medema-group/BiG-SCAPE#160]
Hello,

I downloaded BiG-SCAPE from here: https://github.com/medema-group/BiG-SCAPE/archive/refs/tags/v1.1.5.zip

When I try to run for only three genomes (antiSMASH outputs) I can run it without any issues. When I expanded the run to all the antiSMASH outputs from this link (https://zenodo.org/records/7402932, file named antismash_only_gbk.zip), I get the following error. Can you help me?

My sklearn version is 1.3.0.

ERROR:

BiG-SCAPE-1.1.5 tiagoferreiraleao$ ./bigscape.py --pfam_dir /Users/tiagoferreiraleao/Desktop/shared_folders/first_principles/coder/single_software/bigscape -i /Users/tiagoferreiraleao/Desktop/shared_folders/first_principles/coder/single_software/bigscape/antismash_only_gbk/ -o /Users/tiagoferreiraleao/Desktop/shared_folders/first_principles/coder/single_software/bigscape/bigscape_output_bornita-240508 -c 4 --include_singletons --mibig

   - - Processing input files - -
 Including files with one or more of the following strings in their filename: 'cluster', 'region'
 Skipping files with one or more of the following strings in their filename: 'final'

[...]

   - - Calculating distance matrix - -
Performing multiple alignment of domain sequences

 Using hmmalign
launch_hmmalign took 1510.139 seconds
 Trying to read domain alignments (*.algn files)

Generating distance network files with ALL available input files
   Writing the complete Annotations file for the complete set

 Working for each BGC class
  Sorting the input BGCs

  Warning: unknown product 'NRP-metallophore'
  Warning: unknown product 'NRP-metallophore'

  RiPPs (2481 BGCs)
   Writing annotation files
   Calculating all pairwise distances
generate_network took 112.080 seconds
   Removing 271 non-relevant MIBiG BGCs
   Writing output files
  Calling Gene Cluster Families
  Cutoff: 0.3
//anaconda3/envs/bigscape_env/lib/python3.7/site-packages/sklearn/cluster/_affinity_propagation.py:253: ConvergenceWarning: Affinity propagation did not converge, this model will not have any cluster centers.
  ConvergenceWarning,
Traceback (most recent call last):
  File "./bigscape.py", line 3261, in <module>
    htmlFolder=network_html_folder)
  File "./bigscape.py", line 1459, in clusterJsonBatch
    labels[bgcExt2Int[bgcSub2Ext_[i]]] = bgcExt2Int[bgcSub2Ext_[exemplarsSub[labelsSub[i]]]]
IndexError: list index out of range

**Comment by jorgecnavarrom** [comment]
Hi Tiago, 

I haven't time to run your dataset yet, but we have encountered issues with more recent versions of scikit-learn (a change in behaviour if it doesn't find an exemplar cluster). Could you try downgrading to v0.19.2 and re-trying?
