### ISSUE TITLE
Package version number needs to be bumped to reflect github release version number

### ISSUE THREAD

**Issue by chasemc** [medema-group/BiG-SCAPE#167]
Release is 1.1.9
Package is 1.1.8

**Comment by tigerxu** [comment]
I met the same issue.
$ python bigscape.py --version
BiG-SCAPE 1.1.8 (2022-11-14)

I downloaded the latest installation file BiG-SCAPE-1.1.9.zip.

**Comment by adraismawur** [comment]
I have finally bumped the version number on 1.1.9, sorry for taking so long.
