### ISSUE TITLE
visualizing the singletons

### ISSUE THREAD

**Issue by AhmedElsherbini** [medema-group/BiG-SCAPE#169]
Hello,

I am working on a big group of genomes  6846 gneomes which has resulted in 8825 BGC. I actually would like to extract rare BGCs (~signletons, ~orphans BGC,rare ..).

My first run was the default without any parameters added. 

In the HTML, the index file, I sew in the singletons in each category like NRPS  
```HTML
Total BGCs: 1000 (10 signelton/s), links: xxxxx , families: xx
```
When I try to load the .Network file in Cytoscpae, I do not see any Singletons.

My first question, is my case the same as this [issue](https://github.com/medema-group/BiG-SCAPE/issues/44)? if I run the with <code>-- include_singletons</code>, my signletons will show in cytoscape. 

I am wondering from the output of BIG-SCAEP, is there a way to extract these signtons without using Cytscope, especially with big runs like mine.

Thank you,
Ahmed

**Comment by jorgecnavarrom** [comment]
Hi,

Yes, I think it's the same case. If I remember correctly, the singletons are always shown in the interactive output, but not on the .network file unless you use `--include_singletons`.

It should be easy to extract these singletons from the .networks file, as their first two columns are repeated (i.e. they are only "connected" to themselves). In Python this should be something like:

```python
#!/usr/bin/env python3
"""
Call this script as
python [name of script].py <bigscape.network file>
"""

from sys import argv

with open(argv[1]) as nt, open("singletons.network", "w") as sgl:
    sgl.write(nt.readline())
    for line in nt:
        node1, node2 = line.split("\t")[:2]
        if node1 == node2:
            sgl.write(line)
```
