### ISSUE TITLE
'ascii' codec can't decode byte 0xce & No sequence extracted

### ISSUE THREAD

**Issue by chengyou96** [medema-group/BiG-SCAPE#18]
Hi, 

First of all, thank you for developing the pipeline! I met several errors when trying to analyze 1418 antiSMASH files in .gbk format.\
Here is the detail:

   - - Processing input files - -
 Output folder already exists
 Logs folder already exists
 Cache folder already exists
 BGC fastas folder already exists
 Domtable folder already exists
 Domains folder already exists
 pfs folder already exists
 pfd folder already exists
 Including files with one or more of the following strings in their filename: 'cluster', 'region'
 Skipping files with one or more of the following strings in their filename: 'final'

 Trying to read bundled MIBiG BGCs as reference
  MIBiG BGCs seem to have been extracted already

Importing MIBiG files
   Error with file /home/apps/software/BiG-SCAPE/1.1.1-IGB-gcc-4.9.4-Python-3.6.1/Annotated_MIBiG_reference/MIBiG_2.1_final/BGC0000199.1.gbk: 
    ''ascii' codec can't decode byte 0xce in position 5255: ordinal not in range(128)'
    (This file will be excluded from the analysis)
   Error with file /home/apps/software/BiG-SCAPE/1.1.1-IGB-gcc-4.9.4-Python-3.6.1/Annotated_MIBiG_reference/MIBiG_2.1_final/BGC0001149.1.gbk: 
    ''ascii' codec can't decode byte 0xe2 in position 5364: ordinal not in range(128)'
    (This file will be excluded from the analysis)
   Error with file /home/apps/software/BiG-SCAPE/1.1.1-IGB-gcc-4.9.4-Python-3.6.1/Annotated_MIBiG_reference/MIBiG_2.1_final/BGC0001231.1.gbk: 
    ''ascii' codec can't decode byte 0xce in position 5461: ordinal not in range(128)'
    (This file will be excluded from the analysis)
   Error with file /home/apps/software/BiG-SCAPE/1.1.1-IGB-gcc-4.9.4-Python-3.6.1/Annotated_MIBiG_reference/MIBiG_2.1_final/BGC0001852.1.gbk: 
    ''ascii' codec can't decode byte 0xce in position 7752: ordinal not in range(128)'
    (This file will be excluded from the analysis)
   Error with file /home/apps/software/BiG-SCAPE/1.1.1-IGB-gcc-4.9.4-Python-3.6.1/Annotated_MIBiG_reference/MIBiG_2.1_final/BGC0001851.1.gbk: 
    ''ascii' codec can't decode byte 0xce in position 7842: ordinal not in range(128)'
    (This file will be excluded from the analysis)
  Warning: Input set has files with no Biosynthetic Genes (affects alignment mode)
   See no_biosynthetic_genes_list.txt

 Starting with 1923 files
 Files that had its sequence extracted: 0

Importing GenBank files

 Starting with 1418 files
 Files that had its sequence extracted: 0

Creating output directories
 SVG folder already exists
 Networks folder already exists

Trying threading on 72 cores

Predicting domains using hmmscan
Traceback (most recent call last):
  File "/home/apps/software/BiG-SCAPE/1.1.1-IGB-gcc-4.9.4-Python-3.6.1/bigscape.py", line 2503, in <module>
    for line in domtablefile.readlines():
  File "/home/apps/software/Python/3.6.1-IGB-gcc-4.9.4/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1418: ordinal not in range(128)

----------------------------------------------
Error 1:  'ascii' codec can't decode byte 0xce
Error 2:   Files that had its sequence extracted: 0

What can be the problems? Hope to hear from you soon!

**Comment by jorgecnavarrom** [comment]
> Error 2: Files that had its sequence extracted: 0

Did you try running BiG-SCAPE previously with the same output folder? The main reason for not extracting sequences is that the program detects they are already there

As for error 1, I am not sure. Someone else had the same issue in another forum (https://github.com/nselem/bigscape-corason/issues/3) but we didn't get to the root of the cause.

Was it working before? How did you install it? Are you using the newest MIBiG reference (`--mibig`) or some of the older reference (`--mibig14 or --mibig13`)? Perhaps I'd suggest starting with the recommendations from the other post first (i.e. remove the "MIBiG_2.1.final" folder, use a different output folder) and then perhaps reinstalling BiG-SCAPE (download the current snapshot https://github.com/medema-group/BiG-SCAPE/archive/refs/heads/master.zip and reinstall the conda environment)

**Comment by chengyou96** [comment]
Thank you for your quick reply!  I ran Big-SCAPE on a remote server and it turned out that the errors are related to the enviroment setup.

For error 1, I solved it by setting for the new UTF-8 terminal support in Lion.
# Setting for the new UTF-8 terminal support in Lion
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
# Setting for the new UTF-8 terminal support in Lion
LC_CTYPE=en_US.UTF-8
LC_ALL=en_US.UTF-8
Error 2 seems to be caused by using an outdated package. By running the latest package, I managed to get the result.

However, I have another question about the BiG-SCAPE result interpretation. I tried to visulize it in Cytoscape.
In the .network file, there are multiple parameters including raw distance, squared similarity, jaccard index, DSS index, adjacency index, raw DSS non-anchor. Which parameter should be used as the edge attribute?

**Comment by jorgecnavarrom** [comment]
Great to hear that it's working now! And thanks for sharing the solution :)

Regarding the network files for Cytoscape, use the raw distance. The other columns are components that lead to that final value.

Cheers!
