### ISSUE TITLE
List index out of range (--mix option)

### ISSUE THREAD

**Issue by charleshefer** [medema-group/BiG-SCAPE#184]
Trying to get the script to complete, I and tried bigscape version 1.1.8 (from a conda install) as well as from a docker images hosted by biocontainers [here](https://biocontainers.pro/tools/bigscape), but I get a list index error. 

Here is my command:

`bigscape -i /intermediate_files/antismash/ -o /intermediate_files/BiG-SCAPE/bigscape_output/ --pfam_dir /intermediate_files/PFAM/ --mode glocal --mibig --cutoffs 0.3 0.7 --include_singletons --cores 64 --mix
`

I get the same list index error: 

```
Mix (6822 BGCs)
  Calculating all pairwise distances
/usr/local/lib/python3.7/site-packages/sklearn/cluster/_affinity_propagation.py:253: ConvergenceWarning: Affinity propagation did not converge, this model will not have any cluster centers.
  ConvergenceWarning,
generate_network took 287.858 seconds
   Removing 1060 non-relevant MIBiG BGCs
  Writing output files
  Calling Gene Cluster Families
  Cutoff: 0.3
Traceback (most recent call last):
  File "/usr/local/bin/bigscape", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/bigscape/__main__.py", line 5, in main
    bigscape.main()
  File "/usr/local/lib/python3.7/site-packages/bigscape/bigscape.py", line 3026, in main
    clanCutoff=options.clan_cutoff, htmlFolder=network_html_folder)
  File "/usr/local/lib/python3.7/site-packages/bigscape/bigscape.py", line 1461, in clusterJsonBatch
    labels[bgcExt2Int[bgcSub2Ext_[i]]] = bgcExt2Int[bgcSub2Ext_[exemplarsSub[labelsSub[i]]]]
IndexError: list index out of range
```

I saw some [previous error reports](https://github.com/medema-group/BiG-SCAPE/issues/13) that suggests downgrading scikit-learn etc, but I have some difficulty resolving dependencies when I start with that. Do you perhaps have an environment.yaml file with the correct version of scikit-learn and the dependencies to try? Or is there a bugfix for the issue that I am missing? Any help will be greatly appreciated.

**Comment by jorgecnavarrom** [comment]
Hi. It could be some setup think with the channel priorities, or the version of some package already installed that doesn't let you downgrade scikit-learn.

Here's the current environment I have: [bigscape.txt](https://github.com/user-attachments/files/17188219/bigscape.txt)
