### ISSUE TITLE
Python version in environment.yml outdated?

### ISSUE THREAD

**Issue by VincentNowak** [medema-group/BiG-SCAPE#2]
Hi there,

first up thanks for maintaining this tool. 
This is not strictly speaking an issue but something you may want to be aware of. I have run into a small issue when following the install instructions on your Wiki. The conda environment was created without problems using `conda 4.9.2` but when running the `python bigscape.py --version` command, I would receive the following error
```
ModuleNotFoundError: No module named 'dataclasses'
```
Looking at possible solutions, I found this issue [https://github.com/fastai/fastai/issues/867](https://github.com/fastai/fastai/issues/867), which suggests it is related to the python version (3.6) specified in the `environment.yml` file. After resolving some conflicts that conda wasn't happy with, I have arrived at the following `environment.yml` file. Ignore the altered name.
```
name: bigscape_update
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10.2
  - hmmer
  - biopython=1.79
  - fasttree
  - numpy
  - scipy
  - networkx
  - scikit-learn=1.0.2
```
Upon completing the build and running the test command, it seems to be functioning except for a deprecation warning.
```
(bigscape_update)$ python ./bigscape.py --version
/nfs/home/nowakvi/.conda/envs/bigscape_update/lib/python3.10/site-packages/Bio/SubsMat/__init__.py:126: BiopythonDeprecationWarning: Bio.SubsMat has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.substitution_matrices as a replacement, and contact the Biopython developers if you still need the Bio.SubsMat module.
  warnings.warn(
BiG-SCAPE 1.1.2 (2021-06-03)
```
To the best of my knowledge, this shouldn't be a problem but I have two questions:
1. Would you expect the version changes I made to affect functionality? 
2. Do you have an alternative solution to solving this error?

Best regards,
Vincent

**Comment by VincentNowak** [comment]
Update:
Running the 'bigscape_update' conda environment created with the above 'environment.yml' file lead to an problem with 'sklearn' and BiG-SCAPE would not complete due to the following (truncated) error:
```
/nfs/home/nowakvi/.conda/envs/bigscape_update/lib/python3.10/site-packages/sklearn/cluster/_affinity_propagation.py:250: ConvergenceWarning: Affinity propagation did not converge, this model will not have any cluster centers.
...
IndexError: list index out of range
``` 
After finding this issue  [https://github.com/scikit-learn/scikit-learn/issues/17657](https://github.com/scikit-learn/scikit-learn/issues/17657), which outlines random states and seeding behaviour across sklearn versions (some of which I don't think I fully understand), I changed python and scikit-learn version again and was able to complete the BiG-SCAPE run on my data. The 'environment.yml' file for the successful run is below.
```
name: bigscape_udpate_2
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.7.1
  - hmmer
  - biopython=1.79
  - fasttree
  - numpy
  - scipy
  - networkx
  - scikit-learn=0.23.1
```
The error report generated from this run contained numerous of the below FutureWarnings, which again relate to the problem with sklearn outlined in the above issue (see error below). While some reservations were voiced about sklearn producing inconsistent results in the above issue, I figured that the 'bigscape_update' version would in fact produce results if given enough attempts at producing the correct seed for affinity propagation and after re-running the clustering steps of BiG-SCAPE several times I got the run to complete on my data. I suppose this in part answers my above question 1. in that functionality is indeed affected but I'm still curious to hear what your thoughts are on how much it would affect the output. In any case, it seems that 'bigscape_udpate_2' version I arrived at should be functional if my installation problems are not an isolated issue.
```
/nfs/home/nowakvi/.conda/envs/bigscape_udpate_2/lib/python3.7/site-packages/sklearn/cluster/_affinity_propagation.py:152: FutureWarning: 'random_state' has been introduced in 0.23. It will be set to None starting from 0.25 which means that results will differ at every function call. Set 'random_state' to None to silence this warning, or to 0 to keep the behavior of versions <0.23.
  FutureWarning)
```

**Comment by loraine-gueguen** [comment]
The python update would be much appreciated to package the tool into Bioconda as well because python 3.6 is EOL. What do you think @jorgecnavarrom ?

**Comment by jorgecnavarrom** [comment]
(Sorry for being so late with this. I haven't had much time to test those versions yet)

**Comment by Chandrima-04** [comment]
Is there any other changes you made @VincentNowak? Using your environment.xml update I am still getting the following issue:

`Traceback (most recent call last):
  File "/home/cb4603/BiG-SCAPE/bigscape.py", line 3283, in <module>
    family_data = clusterJsonBatch(BGC_classes[bgc_class], pathBase, bgc_class,
  File "/home/cb4603/BiG-SCAPE/bigscape.py", line 1771, in clusterJsonBatch
    clanLabels = [familyIdx[exemplarsClans[labelsClans[i]]] for i in range(len(familyIdx))]
  File "/home/cb4603/BiG-SCAPE/bigscape.py", line 1771, in <listcomp>
    clanLabels = [familyIdx[exemplarsClans[labelsClans[i]]] for i in range(len(familyIdx))]
IndexError: list index out of range
`

Do you have any suggestions @jorgecnavarrom ?

**Comment by Chandrima-04** [comment]
I tried with the original Big-SCAPE environment.yml which is giving the same error that you mentioned @VincentNowak, after which I tried a few of my modifications, followed by bigscape_update_2 version. The same error persisted! Is there any other versions which I should be aware of?

**Comment by VincentNowak** [comment]
Hm, that's strange. `bigscape_update_2` has been working fine for me. Not sure if it has something to do with the conda version or any underlying dependencies. I used conda version 4.9.2 and went through the whole install according to the instructions from the [Wiki](https://git.wageningenur.nl/medema-group/BiG-SCAPE/-/wikis/installation) including the preparation of Pfam database on our HPC. Can provide more specs on environment and HPC if you think that would help you @Chandrima-04.

**Comment by jorgecnavarrom** [comment]
Hi all
I think the `ModuleNotFoundError: No module named 'dataclasses'` error must be coming from some of the dependencies, as we don't use `dataclasses` anywhere in the code. This module was introduced in Python 3.7, so upgrading to that would fix the error. 

The sciki-learn version is a bit more complex, as they've introduced changes in more recent versions (as mentioned in #9). Version 0.19.2 adds [support for Python 3.7](https://scikit-learn.org/dev/whats_new/v0.19.html) but doesn't change anything else.

Biopython 1.70 from bioconda doesn't support Python 3.7, so that needs to be upgraded.

I created a conda environment from scratch by doing:
```
conda create --name bigscape_fix python=3.7 scikit-learn=0.19.2
conda install biopython networkx
conda install -c bioconda hmmer fasttree
```
and tested it with a small sample. It ran fine, but there are a few warnings about deprecated things from biopython and numpy. @Chandrima-04 could you try this? In the short term, this should hopefully get rid of errors without requiring more changes.

**Comment by Chandrima-04** [comment]
Thanks, @jorgecnavarrom! The bigscape_fix parameters worked! :)

**Comment by jorgecnavarrom** [comment]
Great to hear it worked!
I'll close this thread for now, and will work on an official mini-release in the near future incorporating compatibility with scikit-learn 1.1.x

**Comment by loraine-gueguen** [comment]
FYI: Bigscape is available as a conda package with all dependencies (python 3.6 for now), that can be installed with `conda install bigscape` (https://bioconda.github.io/recipes/bigscape/README.html)
I am updating the package with python 3.7, following the bigscape_fix conda environment described by @jorgecnavarrom: https://github.com/bioconda/bioconda-recipes/pull/35106

**Comment by jorgecnavarrom** [comment]
Thanks Loraine! Hopefully people won't be confused by the warnings

**Comment by MdUmar-tech** [comment]
I encountered a NameError in BiG-SCAPE while running the tool with conda version 23.11.0. I followed the installation instructions provided in the [bioconda page for BiG-SCAPE](https://anaconda.org/bioconda/bigscape). Here's the command I used:
 python bigscape.py  --inputdir corrected_name --outputdir BiG-SCAPE_mix_sing --mix --pfam_dir /Users/mdumar/Desktop/DM_30/databases  --mibig --include_singletons  

However, I received the following error:
File "/Users/mdumar/Desktop/DM_30/BiG-SCAPE-master/bigscape.py", line 3333, in <module>
    main()
  File "/Users/mdumar/Desktop/DM_30/BiG-SCAPE-master/bigscape.py", line 2522, in main
    parseHmmScan(domtableFile, pfd_folder, pfs_folder, options.domain_overlap_cutoff)
  File "/Users/mdumar/Desktop/DM_30/BiG-SCAPE-master/bigscape.py", line 1294, in parseHmmScan
    info = genbankDict.get(outputbase)
NameError: name 'genbankDict' is not defined

To address this issue, I made the following changes in the code:
global genbankDict
genbankDict = {} #added

def parseHmmScan(domtableFile, pfd_folder, pfs_folder, domain_overlap_cutoff, genbankDict): #modified from 
    outputbase = ".".join(domtableFile.split(os.sep)[-1].split(".")[:-1])
    # following available code 
    
  and called funcion
  parseHmmScan(domtableFile, pfd_folder, pfs_folder, options.domain_overlap_cutoff,genbankDict) #added genbankDict

These changes resolved the NameError for me. Can you confirm if this modification is correct, or if there's a better way to handle this issue? If needed, I can submit a pull request with the changes.

Thanks,

**Comment by MdUmar-tech** [comment]
Hi, next I tried like I just added genbankDict in def parseHmmScan
def parseHmmScan(hmmscanResults, pfd_folder, pfs_folder, overlapCutoff, genbankDict):
    outputbase = ".".join(hmmscanResults.split(os.sep)[-1].split(".")[:-1])
    # rest same code...

    return ""
parseHmmScan(domtableFile, pfd_folder, pfs_folder, options.domain_overlap_cutoff, genbankDict)
, It also worked fine, so please let me know if it correct

**Comment by adraismawur** [comment]
> I also tried by following changes I modified the function definition to accept genbankDict as an argument and pass it when calling the function.
> 
> ```
> def parseHmmScan(hmmscanResults, pfd_folder, pfs_folder, overlapCutoff, genbankDict):
>     outputbase = ".".join(hmmscanResults.split(os.sep)[-1].split(".")[:-1])
>     # rest same code...
> 
>     return ""
> ```
> 
> And I call the parseHmmScan function, to pass the genbankDict variable:
> 
> `parseHmmScan(domtableFile, pfd_folder, pfs_folder, options.domain_overlap_cutoff, genbankDict)`
> 
> , It also worked fine, so please let me know if it correct

Hello,

Yes, there is an issue with that variable not being exposed to the correct scope when running BiG-SCAPE as a module.

We recommend running BiG-SCAPE v1 as a script using `python bigscape.py` instead of installing it and running it directly using `bigscape` or `python -m bigscape`.

See https://github.com/medema-group/BiG-SCAPE/issues/103#issuecomment-1880621938 for further information.

We will be releasing a beta version of BiG-SCAPE v2 in the next few weeks, which will be properly installable and runnable via conda.
