### ISSUE TITLE
cosine distance among BGCs

### ISSUE THREAD

**Issue by neptuneyt** [medema-group/BiG-SCAPE#20]
Dear author，

Is there any way to calculate the cosine distance between two BGCs sequence?

I have try the textdistance of Python library, but the result make no sense.

**Comment by jorgecnavarrom** [comment]
Hi

I'm not really sure, to be honest. Perhaps this could help (see pfam2vec)? https://academic.oup.com/nar/article/47/18/e110/5545735

**Comment by INFINITY1993** [comment]
> Dear author，
> 
> Is there any way to calculate the cosine distance between two BGCs sequence?
> 
> I have try the textdistance of Python library, but the result make no sense.

Hi, neptuneyt,
I have the same problem. Have you resolved this?
Looking forward for your reply! Thanks!

**Comment by marnixmedema** [comment]
Not sure either, but @satriaphd has used cosine distances for BiG-SLICE in our recent study found here: https://www.nature.com/articles/s41564-022-01110-2
Perhaps he can comment on the code used to do this.
