### ISSUE TITLE
Warning: unknown product 'NI-siderophore'

### ISSUE THREAD

**Issue by emorinrae** [medema-group/BiG-SCAPE#204]
Hello,

I'm working on NIS proteins and I have predicted BGCs on 140 genomes with Antismash v7.1.0, version that introduces the NI-siderophore product. When I run BiG-SCAPE on those results I encounter a warning saying : unknown product 'NI-siderophore'.
My question is : is there an impact on the clustering of those proteins labelled as NI-siderophore ? will they match a MiBIG BGC labelled as siderophore ? have you planned on adding this product to a new version of BiG-SCAPE and not in Others ?
Thanks,

Emmanuelle

**Comment by emorinrae** [comment]
Hi,

My questions are still standing, is there an impact on the clustering if the product name is not recognized ?
Thanks,

Emmanuelle

**Comment by jorgecnavarrom** [comment]
Sorry for the late response. All these unrecognized labels will be analyzed in the Others category, which means a change in the weights that make up the final distance number. This implies that the distance is mostly made up of the DSS score (weight=0.97 for Others), which should lead to good clustering results.

As new categories will be appearing, and fine-tuning weights for each will be difficult, the upcoming version 2 of BiG-SCAPE will have a single set of weights
