### ISSUE TITLE
Can’t run on apple silicon

### ISSUE THREAD

**Issue by tyler2d2** [medema-group/BiG-SCAPE#210]
I was trying to analyse a fungus for my dissertation and I can’t for the life of me run it on my can is there any steps I need to do differently

**Comment by jorgecnavarrom** [comment]
Hi

What is the specific problem? Is it something that happens when you run or when you try to install?

**Comment by tyler2d2** [comment]
The docker file fails to build the image I think some of the pathways are expired/ don’t exist anymore

Tyler Adams

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tyler2d2** [comment]
Exit code 100

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jorgecnavarrom** [comment]
tbh I have not tested the docker image on Mac, but the traditional way does work (setting up a conda environment with the requirements): https://github.com/medema-group/BiG-SCAPE/wiki/installation#white_circle-installation-using-conda

**Comment by tyler2d2** [comment]
Should I download Conda and run it in that terminal or just on the computers terminal

**Comment by jorgecnavarrom** [comment]
Do you mean anaconda? What we have tested is to download miniconda, install it and then on a terminal create and activate the environment for BiG-SCAPE

**Comment by tyler2d2** [comment]
But where should I run the code you just sent me because I tried on powershell and docker and they both didn’t work

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jorgecnavarrom** [comment]
You mentioned you were running apple silicon, so all commands from the installation instructions should happen in a Terminal (only difference is you don't have `wget`, but you can download and decompress the source code with your browser)

**Comment by tyler2d2** [comment]
No I’m now on pc

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jorgecnavarrom** [comment]
We haven't tested the docker solution in a while to be honest, and the conda installation won't work on Windows because some packages like hmmer are not available for that platform. I'd recommend trying on the Mac if possible. Otherwise, instaling the [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install) and then following the Linux instructions should work

**Comment by tyler2d2** [comment]
Cool I managed to get a wsl solution working but in the future I will use my Mac, the problem was I was using a document that my supervisor gave me but it wasn’t as useful as the one u gave me :)

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
