### ISSUE TITLE
Singularity Read-only file system Error

### ISSUE THREAD

**Issue by adriangeerre** [medema-group/BiG-SCAPE#22]
Hi,

Thanks for a nice tool. I am using an HPC environment to execute the software. I am using Singularity instead of Docker to run the software. Here is the line of code used:

`singularity run ~/SingularityImages/bigscape.sif -i 00-Data/AntiSMASHgbk/ -o 01-BigScape -c 16 --include_gbk_str '*'`

However, I found and issue when running the software 

**Error:**
```
Traceback (most recent call last):
  File "/usr/src/BiG-SCAPE/bigscape.py", line 2755, in <module>
    SVG(False, os.path.join(svg_folder,bgc+".svg"), handle, bgc, os.path.join(pfd_folder,bgc+".pfd"), True, color_genes, color_domains, pfam_domain_categories, pfam_info, bgc_info[bgc].records, bgc_info[bgc].max_width)
  File "/usr/src/BiG-SCAPE/ArrowerSVG.py", line 663, in SVG
    with open(domains_color_file, "a") as color_domains_handle:
OSError: [Errno 30] Read-only file system: '/usr/src/BiG-SCAPE/domains_color_file.tsv'
```

This issue could not be avoided by using the argument `--writable` provided by singularity.
```
-w, --writable               by default all Singularity containers are
                             available as read only. This option makes
                             the file system accessible as read/write
```

**Error:**
```
singularity run --writable ~/SingularityImages/bigscape.sif -i 00-Data/AntiSMASHgbk/ -o 01-BigScape -c 16 --include_gbk_str '*'
FATAL:   no SIF writable overlay partition found in /faststorage/home/agomez/SingularityImages/bigscape.sif
```

If possible, could you help me to modify the code to run bigscape.py without suffering this issue? Thanks very much!!

**Comment by adriangeerre** [comment]
Hi again,

Thanks for the answer. I have been able to modify the docker image and run BiG-SCAPE in singularity. I am posting the steps for others to access the solution or provide a better one.

- curl -q https://git.wageningenur.nl/medema-group/BiG-SCAPE/raw/master/run_bigscape > run_bigscape
- singularity pull bigscape.sif docker://docker-registry.wur.nl/medema-group/big-scape:1.1.2
- singularity build --sandbox BiGSCAPE bigscape.sif
- vim BiGSCAPE/usr/src/BiG-SCAPE/ArrowerSVG.py # Comment the lines [657, 663:665]
- singularity build bigscape_mod.sif BiGSCAPE

Once I have the modified image:

`singularity run bigscape_mod.sif -i 00-Data/AntiSMASHgbk/ -o 01-BigScape -c 16 --include_gbk_str '*'`

**Comment by jowodo** [comment]
Hi, 
sorry for commenting on this closed issue, but I just observed, that those lines which should be commented out to avoid the issue are still not commented out in the recent release (1.1.7). Am I missing something? 
Thanks for your time!
