### ISSUE TITLE
bigscape2 installation error

### ISSUE THREAD

**Issue by corkdagga** [medema-group/BiG-SCAPE#227]
Hi,

I am using macOS and trying to install bigscape2 using conda/mamba. I have set my conda installations to use osx-64 as described. I have the following issue (below). I also try to install only python3.11 and get the same error because tzdata is not available. 

(base) 19:53:39 paul@NABI-MAC001:~/terminal/software/BiG-SCAPE$ mamba env create -f environment.yml --platform osx-64
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested tqdm 4.66.1**
  - nothing provides requested sortedcontainers 2.4.0**
  - nothing provides charset-normalizer >=2,<4 needed by requests-2.31.0-py310hecd8cb5_0
  - nothing provides python-tzdata >=2022a needed by pandas-2.1.1-py310h5262a37_0
  - nothing provides tzdata needed by python-3.11.0-h559f36b_0_cpython
  - nothing provides tzdata needed by python-3.10.0-h1248fe1_1_cpython
  - nothing provides tzdata needed by python-3.10.0-h1248fe1_1_cpython

Could not solve for environment specs
The following packages are incompatible
├─ biopython 1.81**  is installable with the potential options
│  ├─ biopython 1.81 would require
│  │  └─ python >=3.8,<3.9.0a0  with the potential options
│  │     ├─ python [3.8.0|3.8.1|...|3.8.8], which can be installed;
│  │     └─ python [3.8.18|3.8.19|3.8.20] would require
│  │        └─ python_abi 3.8.* *_cp38, which can be installed;
│  ├─ biopython 1.81 would require
│  │  └─ python_abi 3.8 *_pypy38_pp73, which requires
│  │     └─ python 3.8.* *_73_pypy, which can be installed;
│  ├─ biopython 1.81 would require
│  │  ├─ pypy3.9 [>=7.3.11 |>=7.3.13 ], which requires
│  │  │  └─ tzdata, which does not exist (perhaps a missing channel);
│  │  └─ python [>=3.10,<3.11.0a0 |>=3.11,<3.12.0a0 |>=3.12,<3.13.0a0 ], which requires
│  │     ├─ pypy3.9 [7.3.11.* |7.3.12.* |7.3.13.* |7.3.15.* ], which cannot be installed (as previously explained);
│  │     └─ tzdata, which does not exist (perhaps a missing channel);
│  └─ biopython 1.81 would require
│     ├─ python >=3.9,<3.10.0a0  but there are no viable options
│     │  ├─ python [3.10.0|3.10.1|...|3.9.9], which cannot be installed (as previously explained);
│     │  └─ python [3.9.10|3.9.12] would require
│     │     └─ python_abi 3.9 *_pypy39_pp73, which can be installed;
│     └─ python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported;
├─ matplotlib 3.8.0**  is not installable because there are no viable options
│  ├─ matplotlib 3.8.0 would require
│  │  ├─ matplotlib-base >=3.8.0,<3.8.1.0a0  but there are no viable options
│  │  │  ├─ matplotlib-base 3.8.0 would require
│  │  │  │  └─ python >=3.9,<3.10.0a0 , which cannot be installed (as previously explained);
│  │  │  ├─ matplotlib-base 3.8.0 would require
│  │  │  │  └─ python [>=3.10,<3.11.0a0 |>=3.11,<3.12.0a0 |>=3.12,<3.13.0a0 ], which cannot be installed (as previously explained);
│  │  │  └─ matplotlib-base 3.8.0 would require
│  │  │     └─ importlib-resources >=3.2.0 , which does not exist (perhaps a missing channel);
│  │  └─ python >=3.9,<3.10.0a0 , which cannot be installed (as previously explained);
│  ├─ matplotlib 3.8.0 would require
│  │  ├─ pypy3.9 [>=7.3.12 |>=7.3.13 ], which cannot be installed (as previously explained);
│  │  └─ python [>=3.10,<3.11.0a0 |>=3.11,<3.12.0a0 |>=3.12,<3.13.0a0 ], which cannot be installed (as previously explained);
│  └─ matplotlib 3.8.0 would require
│     ├─ matplotlib-base >=3.8.0,<3.8.1.0a0 , which cannot be installed (as previously explained);
│     ├─ python >=3.9,<3.10.0a0 , which cannot be installed (as previously explained);
│     └─ python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported;
├─ networkx 3.1**  is installable with the potential options
│  ├─ networkx 3.1 would require
│  │  └─ python >=3.8,<3.9.0a0  with the potential options
│  │     ├─ python [3.8.0|3.8.1|...|3.8.8], which can be installed;
│  │     └─ python [3.8.18|3.8.19|3.8.20], which can be installed (as previously explained);
│  ├─ networkx 3.1 would require
│  │  └─ python [>=3.10,<3.11.0a0 |>=3.11,<3.12.0a0 |>=3.12,<3.13.0a0 ], which cannot be installed (as previously explained);
│  └─ networkx 3.1 would require
│     └─ python >=3.9,<3.10.0a0 , which cannot be installed (as previously explained);
├─ numpy 1.26.0**  is not installable because there are no viable options
│  ├─ numpy 1.26.0 would require
│  │  └─ numpy-base [1.26.0 py39ha186be2_0|1.26.0 py39hd8f4981_0], which requires
│  │     └─ python >=3.9,<3.10.0a0 , which cannot be installed (as previously explained);
│  ├─ numpy 1.26.0 would require
│  │  ├─ pypy3.9 >=7.3.12 , which cannot be installed (as previously explained);
│  │  └─ python [>=3.10,<3.11.0a0 |>=3.11,<3.12.0a0 |>=3.12,<3.13.0a0 |>=3.12.0rc3,<3.13.0a0 ], which cannot be installed (as previously explained);
│  └─ numpy 1.26.0 would require
│     ├─ python >=3.9,<3.10.0a0 , which cannot be installed (as previously explained);
│     └─ python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported;
├─ pandas 2.1.1**  is not installable because there are no viable options
│  ├─ pandas 2.1.1 would require
│  │  └─ python-tzdata >=2022a , which does not exist (perhaps a missing channel);
│  └─ pandas 2.1.1 would require
│     └─ python-tzdata >=2022.1 , which does not exist (perhaps a missing channel);
├─ pyhmmer 0.10.14**  is installable with the potential options
│  ├─ pyhmmer 0.10.14 would require
│  │  └─ python >=3.8,<3.9.0a0  with the potential options
│  │     ├─ python [3.8.0|3.8.1|...|3.8.8], which can be installed;
│  │     └─ python [3.8.18|3.8.19|3.8.20], which can be installed (as previously explained);
│  ├─ pyhmmer 0.10.14 would require
│  │  └─ python [>=3.10,<3.11.0a0 |>=3.11,<3.12.0a0 |>=3.12,<3.13.0a0 ], which cannot be installed (as previously explained);
│  └─ pyhmmer 0.10.14 would require
│     ├─ python >=3.9,<3.10.0a0 , which cannot be installed (as previously explained);
│     └─ python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported;
├─ python 3.11** , which cannot be installed (as previously explained);
├─ requests 2.31.0**  is not installable because it requires
│  └─ charset-normalizer >=2,<4 , which does not exist (perhaps a missing channel);
├─ scipy 1.11.3**  is not installable because there are no viable options
│  ├─ scipy 1.11.3 would require
│  │  └─ python >=3.9,<3.10.0a0 , which cannot be installed (as previously explained);
│  ├─ scipy 1.11.3 would require
│  │  ├─ pypy3.9 [>=7.3.12 |>=7.3.13 ], which cannot be installed (as previously explained);
│  │  └─ python [>=3.10,<3.11.0a0 |>=3.11,<3.12.0a0 |>=3.12,<3.13.0a0 ], which cannot be installed (as previously explained);
│  └─ scipy 1.11.3 would require
│     └─ python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported;
├─ sortedcontainers 2.4.0**  does not exist (perhaps a typo or a missing channel);
└─ tqdm 4.66.1**  does not exist (perhaps a typo or a missing channel).

(base) 20:00:00 paul@NABI-MAC001:~/terminal/software/BiG-SCAPE$

**Comment by corkdagga** [comment]
Some good news and bad news. 

Firstly, I fixed the error above. I think it was because my conda was not the latest version. I had to delete and reinstall conda and mamba, they are now the latest versions and creating the environment using the environment.yml file as described seemed to work fine.

However, when I go to the next step (pip install .) - I get the following error: 

(base) 20:48:33 paul@NABI-MAC001:~$ conda activate bigscape
(bigscape) 20:48:36 paul@NABI-Mcd terminal/software/BiG-SCAPE/
(bigscape) 20:48:51 paul@NABI-MAC001:~/terminal/software/BiG-SCAPE$ pip install .
Processing /Users/paul/terminal/software/BiG-SCAPE
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/opt/homebrew/Caskroom/miniforge/base/envs/bigscape/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/homebrew/Caskroom/miniforge/base/envs/bigscape/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Caskroom/miniforge/base/envs/bigscape/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/dh/t40tpvlj397ghr6t2y35rdjh0000gq/T/pip-build-env-bbp91vsw/overlay/lib/python3.11/site-packages/hatchling/build.py", line 58, in build_wheel
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/dh/t40tpvlj397ghr6t2y35rdjh0000gq/T/pip-build-env-bbp91vsw/overlay/lib/python3.11/site-packages/hatchling/builders/plugin/interface.py", line 90, in build
          self.metadata.validate_fields()
        File "/private/var/folders/dh/t40tpvlj397ghr6t2y35rdjh0000gq/T/pip-build-env-bbp91vsw/overlay/lib/python3.11/site-packages/hatchling/metadata/core.py", line 265, in validate_fields
          _ = self.version
              ^^^^^^^^^^^^
        File "/private/var/folders/dh/t40tpvlj397ghr6t2y35rdjh0000gq/T/pip-build-env-bbp91vsw/overlay/lib/python3.11/site-packages/hatchling/metadata/core.py", line 149, in version
          self._version = self._get_version()
                          ^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/dh/t40tpvlj397ghr6t2y35rdjh0000gq/T/pip-build-env-bbp91vsw/overlay/lib/python3.11/site-packages/hatchling/metadata/core.py", line 260, in _get_version
          raise ValueError(message) from None
      ValueError: Invalid version `release/2.0.0` from field `project.version`, see https://peps.python.org/pep-0440/
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(bigscape) 20:48:56 paul@NABI-MAC001:~/terminal/software/BiG-SCAPE$

**Comment by adraismawur** [comment]
Whoops! Looks like I made a mistake in setting the version number of BiG-SCAPE. But you should be able to run it still using 

`python bigscape.py [mode] [arguments]`

 in the command line when you are in the BiG-SCAPE directory.

**Comment by adraismawur** [comment]
This should be resolved with the latest update.
