### ISSUE TITLE
Error while running BiG-SCAPE

### ISSUE THREAD

**Issue by AmayAgrawal** [medema-group/BiG-SCAPE#23]
Hi,

I installed BiG-SCAPE (v1.1.5) using conda and trying to use this on my antismash output. However, the execution of the program halts with the following error:

> launch_hmmalign took 13.121 seconds
 Trying to read domain alignments (*.algn files)
Traceback (most recent call last):
  File "/home/myuser/anaconda3/envs/bigscape/bin/bigscape.py", line 2835, in <module>
    dir_util.copy_tree(os.path.join(os.path.dirname(os.path.realpath(__file__)), "html_template", "output"), output_folder)
  File "/home/myuser/anaconda3/envs/bigscape/lib/python3.7/site-packages/setuptools/_distutils/dir_util.py", line 139, in copy_tree
    raise DistutilsFileError("cannot copy tree '%s': not a directory" % src)
distutils.errors.DistutilsFileError: cannot copy tree '/home/myuser/anaconda3/envs/bigscape/bin/html_template/output': not a directory

I am using the following command to run the analysis `python3 bigscape.py -i gbk/ -o analysis/ --pfam_dir ./ -c 16`

Can someone please help me with this?

**Comment by jorgecnavarrom** [comment]
Hi @AmayAgrawal 
Did you install BiG-SCAPE directly from conda? There is indeed an error when installing directly. I haven't had the chance to fix this yet, but I'd recommend the 'traditional' installation for the time being -i.e. installing all the dependencies using conda, then cloning the code, https://github.com/medema-group/BiG-SCAPE/wiki/installation#white_circle-installation-using-conda

**Comment by AmayAgrawal** [comment]
Hi @jorgecnavarrom 
Yes I installed it directly from conda and somehow figured out last week only that some of the folders that the software needed to run were missing. So, downloaded it from github and got the code to work. Thanks for your suggestion as well

**Comment by bdelepine** [comment]
Hello !
I run into the same error installing from the non-recommended [bioconda repo](https://anaconda.org/bioconda/bigscape). I suggest:

* deleting or adding a warning to the bioconda repo stating that it should not be used,
* or adding a warning [in the wiki](https://github.com/medema-group/BiG-SCAPE/wiki/installation#white_circle-installation-using-conda),
* or fixing the bioconda recipe as installation through conda seems like a desirable feature.

The [bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/5631abb760d65070f874fb19b3eb7e41fac4a881/recipes/bigscape/meta.yaml) uses pip and [setup.py](https://github.com/medema-group/BiG-SCAPE/blob/master/setup.py) to install BiG-SCAPE. It looks like there are two issues with this file:

* the version number is wrong (https://github.com/medema-group/BiG-SCAPE/blob/master/setup.py#L20),
* `bigscape.py` is exposed (https://github.com/medema-group/BiG-SCAPE/blob/master/setup.py#L25) but datafiles (`html_template/`) are not, which causes the `distutils.errors.DistutilsFileError` as BiG-SCAPE assumes the datafiles will be in the script's folder (https://github.com/medema-group/BiG-SCAPE/blob/master/bigscape.py#L2835). You may consider using [package_dir or data_files options](https://docs.python.org/3/distutils/setupscript.html#installing-package-data) in `setup.py`.

HTH, best
