### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by SSxlei** [medema-group/BiG-SCAPE#27]
I recently tried to use bigscape to run a very large data set, about 280,000 BGCs, and it will prompt 'memory error' when finally calculating the distance, which seems to be the problem of insufficient memory. I tried to use 2T of memory to run it, but it still hasn't been solved. Or does bigscape support multi-node collaboration? This will expand my inventory.

![output](https://user-images.githubusercontent.com/118705094/223595158-b7c27d11-649a-43b8-9a0e-5628bb0565c0.png)

**Comment by jorgecnavarrom** [comment]
Hi

That's quite a big data set... Here are some things that might help:
* Reduce the number of cpus. Some very large data structures need to be copied to each parallel thread, so this might help
* Try separating the analysis into different runs, one for each biosynthetic class. You can do that by using the `--banned_classes` parameter (and removing all but one class)
* I've heard of cases where people use the dereplication step from BiG-MAP (https://journals.asm.org/doi/10.1128/mSystems.00937-21) to reduce the number of very similar regions
* If this is not enough, you could also consider BiG-SLICE (https://academic.oup.com/gigascience/article/10/1/giaa154/6092777), which will scale much better

As a side note, I'd never seen the first error ("Target sequence length > 100K, over comparison pipeline limit"). I'm not sure if that is related to BiG-SCAPE
