### ISSUE TITLE
Archive tar.gz for release 1.1.3 ?

### ISSUE THREAD

**Issue by loraine-gueguen** [medema-group/BiG-SCAPE#3]
Thank you for adding the setup.py addition file !

Could you please create a tag for the new release 1.1.3 in the repo (https://github.com/medema-group/BiG-SCAPE/tags) in order to have a tar.gz archive, that is needed to build the Bioconda package.

Thanks!

Loraine

**Comment by jorgecnavarrom** [comment]
done!
