### ISSUE TITLE
MIBiG subnetworks not pruned

### ISSUE THREAD

**Issue by jorgecnavarrom** [medema-group/BiG-SCAPE#30]
If multiple cutoff values are chosen, and if MIBiG BGCs are connected with input regions in the higher-value cutoffs, they will be kept, even if they form separate subnetworks and should be pruned in lower-valued cutoffs

**Comment by adraismawur** [comment]
We have released a beta version of BiG-SCAPE 2 which addresses this issue.

Please try using that version, and please feel free to report any issues!
