### ISSUE TITLE
BGCs missing in network

### ISSUE THREAD

**Issue by liangzhengjiao** [medema-group/BiG-SCAPE#44]
my input data include 5 BGCs，but only 3 present in Network. What happen to the other 2 ?

**Comment by jorgecnavarrom** [comment]
Do you mean the output .network files? It's possible that they were not connected to any other region (at the specified cutoff), and are not shown by default. You can include them by using the `--include_singletons` flag in the parameters (https://github.com/medema-group/BiG-SCAPE/wiki/parameters#include-singletons)

**Comment by adraismawur** [comment]
Hi! We are closing issues after a while of inactivity. Please don't hesitate to re-open this issue if necessary!
