### ISSUE TITLE
BiG-SCAPE recognises gbk file but does not extract sequences

### ISSUE THREAD

**Issue by Rowena-h** [medema-group/BiG-SCAPE#45]
I installed BiG-SCAPE using the Singularity recipe shared in #26 and ran it with the following command:

```
singularity exec ~/programmes/big-scape/big-scape.img python /usr/src/BiG-SCAPE/bigscape.py \
        -i ../scratch/functional_annotation/002_antismash/${strain_file} \
        --include_gbk_str ${strain_file}_antismash \
        -o ${out_dir} \
        -c ${SLURM_CPUS_PER_TASK}
```

It seems to recognise my antiSMASH input `.gbk` file but does not extract sequences from it

```
  - - Processing input files - -
 Output folder already exists
 Logs folder already exists
 Cache folder already exists
 BGC fastas folder already exists
 Domtable folder already exists
 Domains folder already exists
 pfs folder already exists
 pfd folder already exists
 Including files with one or more of the following strings in their filename: 'Gt-19d1_antismash'
 Skipping files with one or more of the following strings in their filename: 'final'

Importing GenBank files

 Starting with 1 files
 Files that had its sequence extracted: 0
```

Which ultimately results in this error message:

```
   - - Calculating distance matrix - -
Performing multiple alignment of domain sequences
 No domain fasta files found to align
 Trying to read domain alignments (*.algn files)
No aligned sequences found in the domain folder (run without the --skip_ma parameter or point to the correct output folder)
```

Any ideas? Thanks very much in advance.

**Comment by jorgecnavarrom** [comment]
I haven't really used singularity, but the first thing that comes to mind would be to make sure that all the files you're analyzing contain the `include` string (in this case, `Gt-19d1_antismash`). By default, the antiSMASH extracted regions will have the `region` substring, so it's usually not needed to change the `include` parameter

**Comment by Rowena-h** [comment]
Aaah thanks so much, I was misunderstanding the way it deals with file names! As you say I didn't need to specify the string I was giving it.
