### ISSUE TITLE
The error "did not find file MIBiG_1.4_final.zip"

### ISSUE THREAD

**Issue by TadnLee** [medema-group/BiG-SCAPE#48]
Hi, I met the error "did not find file MIBiG_1.4_final.zip". Could you please help me figure out a possible solution?

**Comment by adraismawur** [comment]
Hello!

That is strange. How did you install and run BiG-SCAPE? The file in question should be included in the repository, or should be available through the docker image.

**Comment by dfl5440** [comment]
Hi I have this exact same error except for 3.1. I installed following the githubs wiki installation guide using miniconda
