### ISSUE TITLE
NameError: name 'bgc_fasta_folder' is not defined

### ISSUE THREAD

**Issue by alpole23** [medema-group/BiG-SCAPE#90]
Hi developers,

I am running into an issue with BiG-SCAPE v1.1.5. I installed it into a conda environment and tried to run using some test output from antismash. The inputs to BiG-SCAPE are twelve .gbk files output from an antismash6 run of three _E. coli_ genomes that are contained in the "bigscape" folder. I uninstalled and reinstalled BiG-SCAPE using the conda package, but I keep running into the `bgc_fasta_folder` is not defined error when I run the following command line prompt.

`bigscape --inputdir ./bigscape --outputdir example_output --pfam_dir ./multismash/pfam`

![Capture](https://github.com/medema-group/BiG-SCAPE/assets/151235545/a4076ab8-364c-4c7e-90b6-76414af365d7)

Any help on fixing the error is appreciated. Thanks for your time.

**Comment by adraismawur** [comment]
Hello,

Sorry to hear that the Bioconda install is (still) broken. We will try to fix this issue ASAP.

In the meantime, could you try downloading the previous version? 
https://github.com/medema-group/BiG-SCAPE/archive/refs/tags/v1.1.5.zip

That should still work when running biscape.py directly.

**Comment by adraismawur** [comment]
The bioconda package should soon update with the fixes included in the new release.

**Comment by alpole23** [comment]
I downloaded and installed the package from [https://github.com/medema-group/BiG-SCAPE/archive/refs/tags/v1.1.5.zip](url) and I ran into the following error after the command 

`bigscape.py --inputdir ./bigscape --outputdir example_output --pfam_dir ./multismash/pfam`

![Capture](https://github.com/medema-group/BiG-SCAPE/assets/151235545/9addf975-7d2d-4869-8b4f-08a973211ecc)

Not sure what I am doing wrong here...

**Comment by G-Molano-LA** [comment]
Hi, thanks for the amazing tool!

I just want to note that the conda package `bioconda::bigscape==1.1.6` still presents this problem:

`~$ bigscape --verbose --mibig  --include_gbk_str region HMBGC   --cutoffs 0.6    --clan_cutoff 0.6 0.8    --pfam_dir ../results/bgc/bigscape/pfam    --cores 100             --inputdir ../results/bgc/antismash/   --outputdir ../results/bgc/bigscape/results             &> ../results/bgc/bigscape/log.txt`

`Importing MIBiG files
Traceback (most recent call last):
  File "/home/lalegm/repos/plsdb_update/workflow/.snakemake/conda/39b9269b3f77dd0dbbbdd26e527c21b2_/bin/bigscape", line 10, in <module>
    sys.exit(main())
  File "/home/lalegm/repos/plsdb_update/workflow/.snakemake/conda/39b9269b3f77dd0dbbbdd26e527c21b2_/lib/python3.7/site-packages/bigscape/__main__.py", line 5, in main
    bigscape.main()
  File "/home/lalegm/repos/plsdb_update/workflow/.snakemake/conda/39b9269b3f77dd0dbbbdd26e527c21b2_/lib/python3.7/site-packages/bigscape/bigscape.py", line 2362, in main
    ['*'], exclude_gbk_str, bgc_info)
  File "/home/lalegm/repos/plsdb_update/workflow/.snakemake/conda/39b9269b3f77dd0dbbbdd26e527c21b2_/lib/python3.7/site-packages/bigscape/bigscape.py", line 443, in get_gbk_files
    if process_gbk_files(filepath, min_bgc_size, bgc_info, files_no_proteins, files_no_biosynthetic_genes):
  File "/home/lalegm/repos/plsdb_update/workflow/.snakemake/conda/39b9269b3f77dd0dbbbdd26e527c21b2_/lib/python3.7/site-packages/bigscape/bigscape.py", line 94, in process_gbk_files
    outputfile = os.path.join(bgc_fasta_folder, clusterName + '.fasta')
NameError: name 'bgc_fasta_folder' is not defined`
