### ISSUE TITLE
How to update Big-scape

### ISSUE THREAD

**Issue by Subhajeet1997** [medema-group/BiG-SCAPE#94]
About two years ago, I installed big-scape 1.1.2 as a docker image on my Ubuntu server. Mibig-2.1 is the default database being used by it. Mibig-3.1 is now available. How can I use the freshly released mibig database by updating my big-scape?

**Comment by CatarinaCarolina** [comment]
Hi!
MIBiG 3.1 is available with releases 1.1.5 and above.
Alternatively you may also download the MIBiG processed reference (https://github.com/medema-group/BiG-SCAPE/blob/master/Annotated_MIBiG_reference/MIBiG_3.1_final.zip) and add it to your 1.1.2 /Annotated_MIBiG_reference folder.

**Comment by Subhajeet1997** [comment]
The second point is done by myself. The MIBiG_3.1_final.zip file has been downloaded and is now located in the Annotated_MIBiG_reference folder. It is still using the MIBiG 2.1 version. How it is still operating on the older version even after removing the MIBiG 2.1 database from the reference folder is beyond me. Perhaps I should use Docker to reinstall the latest version. Will the prior version be buried if I do this?

**Comment by CatarinaCarolina** [comment]
The easiest would indeed be to install the latest version, as long as you give the new container a different name there should be no issues.
