### ISSUE TITLE
Issue with input using WSL

### ISSUE THREAD

**Issue by Kartikj112** [medema-group/BiG-SCAPE#97]
Greetings Developers

I am new to bioinformatics so please pardon my rookie issue.

I am trying to run Bigscape using a Windows Subsystem for Linux (because I'm comfortable with Linux CLI). I installed Bigscape and all the requirements. I ran it with a smaller test dataset and it ran successfully. I tried doing it with a different dataset and it not detecting the .genbank files. My input files have the keyword "region" in them (example input file name: AFWF01000004.1.region001). 

Any help would be appretiated.

Thanks 

```
(base) kartikj112@Mach3:~/BiG-SCAPE-1.1.5$ python bigscape.py -i home/kartikj112/BiG-SCAPE-1.1.5/gbksinside -o output


   - - Processing input files - -
 Including files with one or more of the following strings in their filename: 'cluster', 'region'
 Skipping files with one or more of the following strings in their filename: 'final'

Importing GenBank files

 Starting with 0 files
 Files that had its sequence extracted: 0

Creating output directories

Trying threading on 16 cores

Predicting domains using hmmscan
 All fasta files had already been processed
 Finished generating domtable files.

Parsing hmmscan domtable files
 All domtable files had already been processed
 Finished generating pfs and pfd files.

Processing domains sequence files
 Adding sequences to corresponding domains file
 Reading the ordered list of domains from the pfs files
 Creating arrower-like figures for each BGC
  Parsing hmm file for domain information
    Done
  All SVG from the input files seem to be in the SVG folder
 Finished creating figures


   - - Calculating distance matrix - -
Performing multiple alignment of domain sequences
 No domain fasta files found to align
 Trying to read domain alignments (*.algn files)
No aligned sequences found in the domain folder (run without the --skip_ma parameter or point to the correct output folder)
```

**Comment by adraismawur** [comment]
Hello!

Strange! WSL usually works very well.
Could you describe/show what the folder with your .gbk files look like?

**Comment by Kartikj112** [comment]
Hi

I'm attaching a screenshot of my input folder if it helps.


![Screenshot 2023-11-29 151244](https://github.com/medema-group/BiG-SCAPE/assets/100703727/f16b6764-1357-451b-9b69-c1a0b9a573f8)

**Comment by adraismawur** [comment]
Do these files end in ```.genbank```?

If so, try renaming the files to end in ```.gbk```. BiG-SCAPE does not accept files ending in ```.genbank```.

**Comment by Kartikj112** [comment]
This worked.  
I assumed that the file format wouldn't matter because .gbk and .genbank are the same thing.

Thanks a lot.
